site_name: 'MESH documentation'
site_author: 'Kaifeng Chen'

repo_name: 'kfrancischen/MESH'
repo_url: 'https://github.com/kfrancischen/MESH'

copyright: 'Copyright &copy; 2016 - 2018 Kaifeng Chen'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/kfrancischen'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/kaifeng-chen-b37a2b69/'

google_analytics:
  - 'UA-40321028-1'
  - 'auto'

python:
   version: 2 # for unicode
   setup_py_install: true

#the third-party extenison mdx_math.py comes with a setup.py script
# Thank you Dmitry Shachnev (https://github.com/mitya57/python-markdown-math)
markdown_extensions:
    - toc:
        permalink: true
    - mdx_math:
        enable_dollar_delimiter: True #for use of inline $..$
    - fenced_code
    - codehilite
    - footnotes
    - admonition

# Required to load the MathJax javascript for the mdx_math.py
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML', 'mathjaxhelper.js']

pages:
- Home: 'index.md'
- Overview:
  - 'Equations & Features': 'features.md'
  - 'Installation': 'installation.md'
- Lua API:
  - 'Base Class': 'LuaAPI/baseClass.md'
  - 'SimulationPlanar': 'LuaAPI/planar.md'
  - 'SimulationGrating': 'LuaAPI/grating.md'
  - 'SimulationPattern': 'LuaAPI/pattern.md'
- Python API:
  - 'Base Class': 'PythonAPI/baseClass.md'
  - 'SimulationPlanar': 'PythonAPI/planar.md'
  - 'SimulationGrating': 'PythonAPI/grating.md'
  - 'SimulationPattern': 'PythonAPI/pattern.md'
- C++ API:
  - 'Classes and Functions': 'C++API/classAndFunction.md'
- Examples:
  - 'Tutorial Example': 'Examples/tutorial.md'
  - 'Single Plane Far-field': 'Examples/planeFarField.md'
  - 'Two Planes Near-field': 'Examples/planeNearField.md'
  - 'Anisotropic Material Near-field': 'Examples/anisotropic.md'
  - 'Iterate Over Gaps Near-field': 'Examples/iterate.md'
  - 'Two Gratings Near-field': 'Examples/gratingNearField.md'
  - 'Two Rectangle Patterns Near-field': 'Examples/rectangleNearField.md'
  - 'Mixed Patterns Near-field': 'Examples/mixedNearField.md'
  - 'Contained Patterns Near-field': 'Examples/containedPattern.md'
  - 'MPI Example': 'Examples/MPI.md'
- Developer: 'develop.md'
- About: 'about.md'

theme: 'material'
